server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/emotunes
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver