spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  kafka:
    bootstrap-servers: localhost:9092

app:
  config:
    azure:
      client-id: 13fed7d8-2085-44d8-b1c2-530cd8b8c747
      client-secret: 902bc5c7-b571-45cf-83c7-a28cc898d600
      tenant-id: 7374920a-88bf-4474-9dfe-c0a4b3c5316e
      storage-id: /subscriptions/6e56fcf6-8e88-4090-83de-8a0f4bdd2a05/resourceGroups/Raj/providers/Microsoft.Storage/storageAccounts/emotunes
      storage-endpoint: https://emotunes.blob.core.windows.net/

azure:
  storage:
    connection:
      string: "BlobEndpoint=https://emotunes.blob.core.windows.net/;QueueEndpoint=https://emotunes.queue.core.windows.net/;FileEndpoint=https://emotunes.file.core.windows.net/;TableEndpoint=https://emotunes.table.core.windows.net/;SharedAccessSignature=sv=2021-12-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-04-28T14:13:55Z&st=2023-04-28T06:13:55Z&spr=https,http&sig=UlcKWBqyPso7EX%2BLcRZZ0oiJoSv9U%2BLzzFP0AusSGMs%3D"
