spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  kafka:
    bootstrap-servers: localhost:9092
#<<<<<<< HEAD
#  azure:
#    storage:
#      connection-string: "DefaultEndpointsProtocol=https;AccountName=emotunes;AccountKey=s+BEmpxTFEJZKwpBl5Bo+NdI9zqiwGiQ4fRNOiC7MGJpMLH1/GwfUfj55OqewrJjjBs39G9IFQ6U+AStbmm5cg==;EndpointSuffix=core.windows.net"
azure:
  storage:
    connection-string: "DefaultEndpointsProtocol=https;AccountName=emotunes;AccountKey=5+LpG0Rdrq3aLgMNtTYRXBQ/kl3YANr6css/8Cm/dNG1Lbx4i0LOREZvpxiwi12X1W9YnvZdJWfy+ASt8JU2Wg==;EndpointSuffix=core.windows.net"
