spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServerDialect
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
  datasource:
    url: jdbc:sqlserver://emotunes-prod.database.windows.net:1433;database=emotunes;user=emotunes@emotunes-prod;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  kafka:
    bootstrap-servers: localhost:9092
