spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://emotunes.mysql.database.azure.com:3306/{your_database}?useSSL=true";
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  kafka:
    bootstrap-servers: localhost:9092
