spring:
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.SQLServerDialect
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  kafka:
    bootstrap-servers: localhost:9092
